use std::fmt;

#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    // Keywords
    Scan,
    Compare,
    Where,
    And,
    Or,
    Not,
    In,
    Generate,
    Find,
    Alert,
    Analyse,
    Convert,
    Using,
    For,
    From,
    Rank,
    Limit,
    By,
    Notify,
    With,
    As,
    Top,
    Asc,
    Desc,
    When,
    Via,
    // Style / platform / framework keywords used as values
    Style,
    Language,
    Framework,
    Platform,
    Message,
    To,

    // Identifiers and literals
    Ident(String),
    StringLit(String),
    IntLit(i64),
    FloatLit(f64),
    ListLit(Vec<String>),
    BoolTrue,
    BoolFalse,

    // Operators
    Dot,
    Comma,
    GreaterThan,
    LessThan,
    GreaterEqual,
    LessEqual,
    Equal,
    NotEqual,
    Percent,
    LeftBracket,
    RightBracket,

    EOF,
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Token::Scan => write!(f, "SCAN"),
            Token::Compare => write!(f, "COMPARE"),
            Token::Where => write!(f, "WHERE"),
            Token::And => write!(f, "AND"),
            Token::Or => write!(f, "OR"),
            Token::Not => write!(f, "NOT"),
            Token::In => write!(f, "IN"),
            Token::Generate => write!(f, "GENERATE"),
            Token::Find => write!(f, "FIND"),
            Token::Alert => write!(f, "ALERT"),
            Token::Analyse => write!(f, "ANALYSE"),
            Token::Convert => write!(f, "CONVERT"),
            Token::Using => write!(f, "USING"),
            Token::For => write!(f, "FOR"),
            Token::From => write!(f, "FROM"),
            Token::Rank => write!(f, "RANK"),
            Token::Limit => write!(f, "LIMIT"),
            Token::By => write!(f, "BY"),
            Token::Notify => write!(f, "NOTIFY"),
            Token::With => write!(f, "WITH"),
            Token::As => write!(f, "AS"),
            Token::Top => write!(f, "TOP"),
            Token::Asc => write!(f, "ASC"),
            Token::Desc => write!(f, "DESC"),
            Token::When => write!(f, "WHEN"),
            Token::Via => write!(f, "VIA"),
            Token::Style => write!(f, "STYLE"),
            Token::Language => write!(f, "LANGUAGE"),
            Token::Framework => write!(f, "FRAMEWORK"),
            Token::Platform => write!(f, "PLATFORM"),
            Token::Message => write!(f, "MESSAGE"),
            Token::To => write!(f, "TO"),
            Token::Ident(s) => write!(f, "Ident({})", s),
            Token::StringLit(s) => write!(f, "\"{}\"", s),
            Token::IntLit(n) => write!(f, "{}", n),
            Token::FloatLit(n) => write!(f, "{}", n),
            Token::ListLit(v) => write!(f, "[{}]", v.join(", ")),
            Token::BoolTrue => write!(f, "true"),
            Token::BoolFalse => write!(f, "false"),
            Token::Dot => write!(f, "."),
            Token::Comma => write!(f, ","),
            Token::GreaterThan => write!(f, ">"),
            Token::LessThan => write!(f, "<"),
            Token::GreaterEqual => write!(f, ">="),
            Token::LessEqual => write!(f, "<="),
            Token::Equal => write!(f, "="),
            Token::NotEqual => write!(f, "!="),
            Token::Percent => write!(f, "%"),
            Token::LeftBracket => write!(f, "["),
            Token::RightBracket => write!(f, "]"),
            Token::EOF => write!(f, "EOF"),
        }
    }
}

pub static KEYWORDS: &[(&str, Token)] = &[
    ("SCAN", Token::Scan),
    ("COMPARE", Token::Compare),
    ("WHERE", Token::Where),
    ("AND", Token::And),
    ("OR", Token::Or),
    ("NOT", Token::Not),
    ("IN", Token::In),
    ("GENERATE", Token::Generate),
    ("FIND", Token::Find),
    ("ALERT", Token::Alert),
    ("ANALYSE", Token::Analyse),
    ("CONVERT", Token::Convert),
    ("USING", Token::Using),
    ("FOR", Token::For),
    ("FROM", Token::From),
    ("RANK", Token::Rank),
    ("LIMIT", Token::Limit),
    ("BY", Token::By),
    ("NOTIFY", Token::Notify),
    ("WITH", Token::With),
    ("AS", Token::As),
    ("TOP", Token::Top),
    ("ASC", Token::Asc),
    ("DESC", Token::Desc),
    ("WHEN", Token::When),
    ("VIA", Token::Via),
    ("STYLE", Token::Style),
    ("LANGUAGE", Token::Language),
    ("FRAMEWORK", Token::Framework),
    ("PLATFORM", Token::Platform),
    ("MESSAGE", Token::Message),
    ("TO", Token::To),
    ("true", Token::BoolTrue),
    ("false", Token::BoolFalse),
];
